language: node_js

install:
  - npm install

script:
  - npm test

after_success:
  - npm run coverage-report

jobs:
  include:
    - stage: test
      os: linux
      node_js: '12'
    - stage: test
      os: linux
      node_js: '8'
    - stage: test
      os: osx
      node_js: '12'
    - stage: test
      os: osx
      node_js: '10'
    - stage: test
      os: windows
      node_js: '10'
    - stage: test
      os: windows
      node_js: '8'
